#!/usr/bin/env python3
"""Writes tests/testdata/hmac_v4_signatures.json: Google's V4 signing
conformance vectors (tests/testdata/v4_signatures.json), signed again with
an HMAC key instead of an RSA one.

Google publishes no HMAC vectors, and of its client libraries only .NET
signs with an HMAC key. But an HMAC-signed URL or POST policy differs from
an RSA one in three places only: the algorithm named, the authorizer in the
credential (an access ID, not an email), and the signature. So each vector's
expected canonical request, or decoded policy, is rewritten in those places
and signed here, with nothing but Python's standard library, by the
derivation Google documents, which this signer was checked against in
production on 2026-10-05: its URLs and a POST policy worked, and its key
derivation matches AWS's published SigV4 example (checked below).

The key is made up, and shaped so no secret scanner takes it for one.

    python3 tools/hmac_vectors.py
"""
import base64
import hashlib
import hmac
import json
import os
import urllib.parse

HERE = os.path.dirname(os.path.abspath(__file__))
SOURCE = os.path.join(HERE, "..", "tests", "testdata", "v4_signatures.json")
OUT = os.path.join(HERE, "..", "tests", "testdata", "hmac_v4_signatures.json")

ACCESS_ID = "GOOG1E-TEST-ONLY-NOT-A-REAL-ACCESS-ID"
SECRET = "TEST_ONLY_not_a_real_secret_000000000000"
EMAIL = "test-iam-credentials@dummy-project-id.iam.gserviceaccount.com"
RSA = "GOOG4-RSA-SHA256"
HMAC = "GOOG4-HMAC-SHA256"
# Google's own data is wrong for this vector: its canonical request keeps
# the bucket in the path its URL moved into the host (tests/storage_signing.zig).
SKIPPED = {"Universe domain with virtual hosted style"}


def signing_key(prefix, secret, date, region, service, request):
    key = hmac.new((prefix + secret).encode(), date.encode(), hashlib.sha256).digest()
    for part in (region, service, request):
        key = hmac.new(key, part.encode(), hashlib.sha256).digest()
    return key


def sign(date, message):
    key = signing_key("GOOG4", SECRET, date, "auto", "storage", "goog4_request")
    return hmac.new(key, message.encode(), hashlib.sha256).hexdigest()


def replace_once(text, old, new):
    assert text.count(old) == 1, (old, text[:200])
    return text.replace(old, new)


def url_vector(v):
    canonical = v["expectedCanonicalRequest"]
    algorithm_line, stamp, scope, digest = v["expectedStringToSign"].split("\n")
    assert algorithm_line == RSA
    # The data's own check: its canonical request is what was signed.
    assert hashlib.sha256(canonical.encode()).hexdigest() == digest, v["description"]
    email = urllib.parse.quote(EMAIL, safe="")
    access_id = urllib.parse.quote(ACCESS_ID, safe="")
    canonical = replace_once(canonical, "X-Goog-Algorithm=" + RSA, "X-Goog-Algorithm=" + HMAC)
    canonical = replace_once(canonical, "X-Goog-Credential=" + email + "%2F", "X-Goog-Credential=" + access_id + "%2F")
    string_to_sign = "\n".join([HMAC, stamp, scope, hashlib.sha256(canonical.encode()).hexdigest()])
    url = v["expectedUrl"]
    url = replace_once(url, "X-Goog-Algorithm=" + RSA, "X-Goog-Algorithm=" + HMAC)
    url = replace_once(url, "X-Goog-Credential=" + email + "%2F", "X-Goog-Credential=" + access_id + "%2F")
    head, _, _ = url.rpartition("&X-Goog-Signature=")
    url = head + "&X-Goog-Signature=" + sign(stamp[:8], string_to_sign)
    return {"description": v["description"], "expectedUrl": url, "expectedStringToSign": string_to_sign}


def policy_vector(v):
    fields = v["policyOutput"]["fields"]
    document = base64.b64decode(fields["policy"]).decode("ascii")
    document = replace_once(document, '"x-goog-algorithm":"' + RSA + '"', '"x-goog-algorithm":"' + HMAC + '"')
    document = replace_once(document, '"x-goog-credential":"' + EMAIL + "/", '"x-goog-credential":"' + ACCESS_ID + "/")
    policy = base64.b64encode(document.encode("ascii")).decode("ascii")
    date = fields["x-goog-date"][:8]
    return {
        "description": v["description"],
        "credential": replace_once(fields["x-goog-credential"], EMAIL + "/", ACCESS_ID + "/"),
        "policy": policy,
        "signature": sign(date, policy),
    }


def main():
    # The derivation, against AWS's published example.
    aws = signing_key("AWS4", "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY", "20120215", "us-east-1", "iam", "aws4_request")
    assert aws.hex() == "f4780e2d9f65fa895f9c67b32ce1baf0b0d8a43505a000a1a9e090d414db404d"
    with open(SOURCE) as f:
        data = json.load(f)
    out = {
        "note": "Generated by tools/hmac_vectors.py from v4_signatures.json; the key is made up.",
        "accessId": ACCESS_ID,
        "secret": SECRET,
        "signingV4Tests": [url_vector(v) for v in data["signingV4Tests"] if v["description"] not in SKIPPED],
        "postPolicyV4Tests": [policy_vector(v) for v in data["postPolicyV4Tests"]],
    }
    with open(OUT, "w") as f:
        json.dump(out, f, indent=1, ensure_ascii=True)
        f.write("\n")
    print(f"wrote {len(out['signingV4Tests'])} URL and {len(out['postPolicyV4Tests'])} POST policy vectors to {OUT}")


if __name__ == "__main__":
    main()
